"""
Global Constants for KSE

Defines system-wide constants and configuration defaults.
"""

# Database Constants
DATABASE_NAME = "kse_db"
DEFAULT_DB_HOST = "localhost"
DEFAULT_DB_PORT = 5432
DEFAULT_DB_USER = "postgres"
DEFAULT_DB_PASSWORD = "postgres"
DB_POOL_MIN_SIZE = 2
DB_POOL_MAX_SIZE = 20

# Domain Constants
MIN_DOMAIN_COUNT = 2543  # Swedish domains
DEFAULT_CRAWL_FREQUENCY_DAYS = 7
DEFAULT_TRUST_SCORE = 0.5

# Crawler Constants
DEFAULT_TIMEOUT = 30  # seconds
MAX_CONTENT_SIZE = 10 * 1024 * 1024  # 10 MB
DEFAULT_USER_AGENT = "KlarSwedishEngine/3.0 (+https://github.com/CKCHDX/klar)"
DEFAULT_MAX_REDIRECTS = 5
DEFAULT_RETRIES = 3
DEFAULT_BACKOFF_FACTOR = 0.5
CRAWLER_BATCH_SIZE = 100  # pages per batch
CRAWLER_THROUGHPUT_TARGET = 100  # pages per minute

# Indexing Constants
TARGET_PAGE_COUNT = 2_800_000  # 2.8 million pages
TARGET_INDEX_SIZE_GB = 4.2  # 4.2 GB
DEFAULT_TOKENIZER_LANGUAGE = "sv"  # Swedish
MIN_TOKEN_LENGTH = 3
MAX_TOKEN_LENGTH = 50

# Search Constants
DEFAULT_SEARCH_TIMEOUT_MS = 500  # 500ms target
DEFAULT_MAX_RESULTS = 100
DEFAULT_RESULT_PAGE_SIZE = 10
MIN_QUERY_LENGTH = 2
MAX_QUERY_LENGTH = 500

# Performance Constants
SEARCH_LATENCY_TARGET_MS = 500  # 99th percentile
QUERY_CACHE_SIZE = 10000
CONCURRENCY_TARGET = 100  # concurrent searches

# System Constants
SYSTEM_LOG_LEVEL = "INFO"
SYSTEM_LOG_RETENTION_DAYS = 30
SNAPSHOT_RETENTION_COUNT = 5
DEFAULT_LOCALE = "sv_SE"

# Uptime Constants
UPTIME_TARGET_PERCENT = 99.9
STABILITY_TEST_HOURS = 72

# Ranking Constants (7-factor algorithm)
RANK_FACTOR_TF_IDF_WEIGHT = 0.25
RANK_FACTOR_PAGERANK_WEIGHT = 0.20
RANK_FACTOR_DOMAIN_AUTHORITY_WEIGHT = 0.15
RANK_FACTOR_RECENCY_WEIGHT = 0.15
RANK_FACTOR_KEYWORD_DENSITY_WEIGHT = 0.10
RANK_FACTOR_LINK_STRUCTURE_WEIGHT = 0.10
RANK_FACTOR_REGIONAL_RELEVANCE_WEIGHT = 0.05

# Pagination Constants
DEFAULT_PAGINATION_LIMIT = 10
MAX_PAGINATION_OFFSET = 10000

# Swedish Language Constants
SWEDISH_LANGUAGE_CODE = "sv"
SWEDISH_LOCALE = "sv_SE"
SWEDISH_ENCODING = "utf-8"

# Production Readiness
MIN_TEST_COVERAGE_PERCENT = 95
CRASH_TOLERANCE_PER_72H = 0
ZERO_DOWNTIME_DEPLOYMENT = True
